name: Bruce Buffer
description: A not great Bruce Buffer impression

1:
  source:
    location: input/Bruce_Buffer_1_0.mp3
    type: file
2:
  source:
    location: input/Bruce_Buffer_1_1.mp3
    type: file
3:
  source:
    location: input/Bruce_Buffer_1_2.mp3
    type: file
4:
  source:
    location: input/Bruce_Buffer_1_3.mp3
    type: file
5:
  source:
    location: input/Bruce_Buffer_1_4.mp3
    type: file
6:
  source:
    location: input/Bruce_Buffer_1_5.mp3
    type: file
