deployments:
- name: DeepfakeRadio
  type: code
  engine: python
  config:
    build:
      commands:
        - "pip install -r requirements.txt" # Install dependencies
        - "chmod +x install_yt_dependency.sh"
        - "./install_yt_dependency.sh"
        - "python main.py" # Run the bot
