name: Barack Obama
description: Former President Barack Obama

1:
  source:
    location: input/obama-1.mp3
    type: file
  clip_size: 30
2:
  source:
    location: input/obama-2.mp3
    type: file
  clip_size: 30