name: Homer Simpson
description: A mid impression of Homer Simpson

1:
  source:
    location: input/Homer_Simpson-1.mp3
    type: file
2:
  source:
    location: input/Homer_Simpson-2.mp3
    type: file
3:
  source:
    location: input/Homer_Simpson-3.mp3
    type: file
4:
  source:
    location: input/Homer_Simpson-4.mp3
    type: file