name: Krusty Krab Training Video

1:
  source:
    location: input/1.mp3
    type: file
2:
  source:
    location: input/2.mp3
    type: file
3:
  source:
    location: input/3.mp3
    type: file
4:
  source:
    location: input/4.mp3
    type: file
5:
  source:
    location: input/5.mp3
    type: file
6:
  source:
    location: input/6.mp3
    type: file
7:
  source:
    location: input/7.mp3
    type: file
8:
  source:
    location: input/8.mp3
    type: file
9:
  source:
    location: input/9.mp3
    type: file
10:
  source:
    location: input/10.mp3
    type: file
11:
  source:
    location: input/11.mp3
    type: file
12:
  source:
    location: input/12.mp3
    type: file
13:
  source:
    location: input/13.mp3
    type: file
14:
  source:
    location: input/14.mp3
    type: file
15:
  source:
    location: input/15.mp3
    type: file
16:
  source:
    location: input/16.mp3
    type: file
17:
  source:
    location: input/17.mp3
    type: file
18:
  source:
    location: input/18.mp3
    type: file
19:
  source:
    location: input/19.mp3
    type: file
20:
  source:
    location: input/20.mp3
    type: file
21:
  source:
    location: input/21.mp3
    type: file
22:
  source:
    location: input/22.mp3
    type: file


